#ifndef HEADFIRSTDESIGNPATTERNS_PIZZATYPES_H
#define HEADFIRSTDESIGNPATTERNS_PIZZATYPES_H

enum class PizzaType
{
    CHEESE,
    PEPPERONI,
    CLAM,
    VEGGIE
};

#endif //HEADFIRSTDESIGNPATTERNS_PIZZATYPES_H
