#ifndef HEADFIRSTDESIGNPATTERNS_IDISPLAYELEMENT_H
#define HEADFIRSTDESIGNPATTERNS_IDISPLAYELEMENT_H

class IDisplayElement
{
public:
    virtual void display() = 0;
};

#endif //HEADFIRSTDESIGNPATTERNS_IDISPLAYELEMENT_H
