#ifndef HEADFIRSTDESIGNPATTERNS_NYSTYLECLAMPIZZA_H
#define HEADFIRSTDESIGNPATTERNS_NYSTYLECLAMPIZZA_H

#include "Pizza.h"


class NYStyleClamPizza : public Pizza
{
public:
    NYStyleClamPizza();

};


#endif //HEADFIRSTDESIGNPATTERNS_NYSTYLECLAMPIZZA_H
