#ifndef HEADFIRSTDESIGNPATTERNS_NYSTYLECHEESEPIZZA_H
#define HEADFIRSTDESIGNPATTERNS_NYSTYLECHEESEPIZZA_H

#include "Pizza.h"

class NYStyleCheesePizza : public Pizza
{
public:
    NYStyleCheesePizza();
};


#endif //HEADFIRSTDESIGNPATTERNS_NYSTYLECHEESEPIZZA_H
