#ifndef HEADFIRSTDESIGNPATTERNS_IQUACKBEHAVIOR_H
#define HEADFIRSTDESIGNPATTERNS_IQUACKBEHAVIOR_H

class IQuackBehavior
{
public:
    virtual void quack() = 0;
};

#endif //HEADFIRSTDESIGNPATTERNS_IQUACKBEHAVIOR_H
